import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Installer from "@/components/Installer";
import Navbar from "@/components/Navbar";
import { SettingsProvider } from "@/contexts/SettingsContext";

async function getSettings() {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000/api';
  try {
    // using no-store to always dynamically fetch the latest backend config changes
    const res = await fetch(`${apiUrl}/settings`, { cache: 'no-store' });
    if (res.ok) return res.json();
  } catch (error) {
    console.warn("Failed to fetch settings from API backend.");
  }
  return {};
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isConfigured = !!process.env.NEXT_PUBLIC_API_URL;
  const settings = await getSettings();

  const primary = settings.primary_color || '#000000';
  const secondary = settings.secondary_color || '#ffffff';
  const accent = settings.accent_color || '#3b82f6';
  
  const headingFont = settings.heading_font || 'Inter';
  const bodyFont = settings.body_font || 'Inter';

  // Build a deduplicated Google Fonts URL (avoid loading same font twice)
  const fontFamilies = [...new Set([headingFont, bodyFont])]
    .map(f => `family=${f.replace(/ /g, '+')}:wght@400;500;600;700;800`)
    .join('&');
  const googleFontsUrl = `https://fonts.googleapis.com/css2?${fontFamilies}&display=swap`;

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href={googleFontsUrl} rel="stylesheet" />
      </head>
      <body
        className={`${geistMono.variable} antialiased`}
        style={{
          '--primary': primary,
          '--secondary': secondary,
          '--accent': accent,
          '--font-heading': `"${headingFont}", sans-serif`,
          '--font-body': `"${bodyFont}", sans-serif`,
          background: secondary,
          color: primary,
        } as React.CSSProperties}
      >
        {isConfigured ? (
          <>
            <SettingsProvider settings={settings}>
              <Navbar settings={settings} />
              {children}
            </SettingsProvider>
          </>
        ) : <Installer />}
      </body>
    </html>
  );
}
